global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'homelab-metric'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nut-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nut-exporter:9185']
